on: 
  issues:
    types: [closed]

name: Glo Close Issue

jobs:
  build:
    name: Glo actions
    runs-on: ubuntu-latest
    steps:
    - uses: Axosoft/glo-action-parse-links@v1
      id: glo-parse

    - uses: Axosoft/glo-action-move-card@v1
      with:
        authToken: ${{ secrets.GLO-PAT }}
        cards: '${{ steps.glo-parse.outputs.cards }}'
        column: 'Done'
      id: glo-move
